repository:
  name: Quantum-NFL
  description: Advanced quantum computing analysis for NFL teams and games
  homepage: https://quantum-nfl.github.io
  topics: quantum-computing, nfl, sports-analytics, python
  private: false
  has_issues: true
  has_projects: true
  has_wiki: true
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true

branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test"
          - "lint"
          - "security"
          - "docs"
          - "build"
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 2
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      restrictions:
        users: []
        teams: 
          - "core-team"
          - "quantum-team"
  
  - name: develop
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "test"
          - "lint"
      enforce_admins: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null

labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"
  
  - name: "enhancement"
    color: "a2eeef"
    description: "New feature or request"
  
  - name: "quantum"
    color: "7057ff"
    description: "Related to quantum systems"
  
  - name: "documentation"
    color: "0075ca"
    description: "Documentation improvements"
  
  - name: "security"
    color: "d93f0b"
    description: "Security related issues"
  
  - name: "performance"
    color: "0e8a16"
    description: "Performance improvements"
