name: GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:  # Manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Generate repository metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: quantum-nfl
          template: classic
          base: header, activity, community, repositories
          plugin_lines: yes
          plugin_traffic: yes
          plugin_stargazers: yes
          plugin_projects: yes
          plugin_code: yes
          
      - name: Generate detailed metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: quantum-nfl
          template: repository
          repo: quantum-nfl
          plugin_languages: yes
          plugin_contributors: yes
          plugin_people: yes
          plugin_followup: yes
          plugin_reactions: yes
          
      - name: Upload metrics
        uses: actions/upload-artifact@v2
        with:
          name: github-metrics
          path: metrics.*
